/****************************************************************************
** Form interface generated from reading ui file 'GenePrediction.ui'
**
** Created: Sat Nov 27 12:05:37 2010
**      by: The User Interface Compiler ($Id: qt/main.cpp   3.3.3   edited Nov 24 2003 $)
**
** WARNING! All changes made in this file will be lost!
****************************************************************************/

#ifndef FORM1_H
#define FORM1_H

#include <qvariant.h>
#include <qpixmap.h>
#include <qframe.h>

class QVBoxLayout;
class QHBoxLayout;
class QGridLayout;
class QSpacerItem;
class QLabel;
class QPushButton;
class QGroupBox;
class QWidgetStack;
class QWidget;
class QButtonGroup;
class QRadioButton;
class QLineEdit;
class QTextEdit;
class QCheckBox;
class QTabWidget;

class Form1 : public QFrame
{
    Q_OBJECT

public:
    Form1( QWidget* parent = 0, const char* name = 0 );
    ~Form1();

    QLabel* textLabel1;
    QPushButton* pushButton74;
    QLabel* sequenceFileName;
    QPushButton* closeSession;
    QFrame* frame6;
    QLabel* textLabel3_4;
    QLabel* textLabel4;
    QGroupBox* groupBox18;
    QWidgetStack* sessionSelectionWg;
    QWidget* WStackPage;
    QPushButton* pushButton78;
    QGroupBox* groupBox37;
    QButtonGroup* buttonGroup15;
    QRadioButton* radioButton33;
    QRadioButton* radioButton34;
    QLineEdit* lineEdit63;
    QPushButton* pushButton75_3;
    QPushButton* pushButton77;
    QWidget* WStackPage_2;
    QGroupBox* groupBox37_2;
    QPushButton* pushButton96;
    QGroupBox* groupBox41;
    QLabel* textLabel3_10;
    QPushButton* browseFile;
    QLineEdit* chooseSeq;
    QGroupBox* groupBox38;
    QButtonGroup* buttonGroup13;
    QRadioButton* radioButton28;
    QRadioButton* radioButton27;
    QRadioButton* radioButton29;
    QLabel* textLabel1_28;
    QPushButton* pushButton76_3;
    QLineEdit* lineEdit64;
    QPushButton* openSession;
    QFrame* frame3;
    QGroupBox* groupBox6;
    QWidgetStack* widgetStack2;
    QWidget* WStackPage_3;
    QWidgetStack* widgetStack;
    QWidget* WStackPage_4;
    QLabel* textLabel3;
    QPushButton* pushButton3;
    QPushButton* computeOrfNowPushButton;
    QWidget* WStackPage_5;
    QGroupBox* groupBox31;
    QButtonGroup* buttonGroup4;
    QRadioButton* radioButton7;
    QRadioButton* radioButton8;
    QGroupBox* groupBox5;
    QLabel* textLabel8;
    QLabel* textLabel9;
    QLineEdit* lineEdit61;
    QLineEdit* lineEdit62;
    QGroupBox* groupBox17_2_2;
    QLabel* textLabel1_2;
    QLabel* textLabel3_2;
    QLabel* textLabel2_2;
    QPushButton* pushButton27;
    QPushButton* pushButton28;
    QLabel* textLabel3_2_2;
    QLineEdit* lineEdit4;
    QLineEdit* lineEdit3;
    QPushButton* pushButton14;
    QWidget* WStackPage_6;
    QButtonGroup* buttonGroup5;
    QRadioButton* radioButton10;
    QRadioButton* radioButton9;
    QPushButton* pushButton16_3;
    QTextEdit* textEdit1;
    QCheckBox* checkBox2;
    QPushButton* pushButton25;
    QWidget* WStackPage_7;
    QLabel* textLabel2_4;
    QLabel* textLabel1_4;
    QPushButton* pushButton26;
    QWidget* WStackPage_8;
    QWidgetStack* widgetStack3;
    QWidget* WStackPage_9;
    QPushButton* pushButton16_4;
    QLabel* textLabel2_3;
    QLabel* textLabel1_3;
    QWidget* WStackPage_10;
    QLabel* textLabel1_5;
    QLabel* textLabel2_5;
    QLineEdit* lineEdit6;
    QLabel* textLabel3_5;
    QLabel* textLabel4_3;
    QLineEdit* lineEdit7;
    QPushButton* pushButton18;
    QLineEdit* lineEdit5;
    QLineEdit* lineEdit4_2;
    QWidget* WStackPage_11;
    QWidgetStack* widgetStack4;
    QWidget* WStackPage_12;
    QTabWidget* tabWidget2;
    QWidget* R_Statistic;
    QLabel* textLabel2_6;
    QPushButton* pushButton74_2;
    QWidgetStack* widgetStack5;
    QWidget* WStackPage_13;
    QGroupBox* groupBox9;
    QLabel* textLabel3_3;
    QLabel* pixmapLabel1_1;
    QLabel* textLabel1_18_3;
    QPushButton* pushButton59;
    QPushButton* pushButton29;
    QGroupBox* groupBox10;
    QLabel* textLabel4_2;
    QLabel* textLabel1_18;
    QPushButton* pushButton29_2;
    QPushButton* pushButton59_2;
    QLabel* pixmapLabel1_2;
    QGroupBox* groupBox11;
    QLabel* textLabel5_2;
    QLabel* pixmapLabel1_3;
    QLabel* textLabel1_18_2;
    QPushButton* pushButton29_3;
    QPushButton* pushButton59_2_2;
    QGroupBox* groupBox12;
    QLabel* textLabel6_2;
    QLabel* pixmapLabel1_4;
    QLabel* textLabel1_18_2_2;
    QPushButton* pushButton29_4;
    QPushButton* pushButton59_2_3;
    QGroupBox* groupBox12_2;
    QLabel* pixmapLabel1_5;
    QLabel* textLabel1_18_2_2_2;
    QLabel* textLabel6_2_2;
    QPushButton* pushButton29_4_3;
    QPushButton* pushButton59_2_3_2;
    QWidget* WStackPage_14;
    QLabel* textLabel1_8;
    QLabel* textLabel5_3;
    QGroupBox* groupBox21;
    QButtonGroup* buttonGroup6;
    QRadioButton* radioButton11;
    QRadioButton* radioButton10_2;
    QGroupBox* groupBox25;
    QLabel* textLabel1_21;
    QLabel* textLabel1_22;
    QLabel* textLabel4_5;
    QLabel* textLabel3_7;
    QLineEdit* lineEdit9;
    QLineEdit* lineEdit8;
    QFrame* frame5;
    QLabel* textLabel7_2;
    QLineEdit* lineEdit11;
    QCheckBox* checkBox3;
    QPushButton* pushButton27_2_5;
    QLineEdit* lineEdit10;
    QFrame* frame10;
    QLineEdit* lineEdit45;
    QLabel* textLabel1_16;
    QPushButton* pushButton35;
    QWidget* threshold_R_Statistics;
    QLabel* textLabel4_6;
    QLabel* textLabel1_10;
    QLabel* textLabel1_9;
    QLabel* textLabel2_9;
    QGroupBox* groupBox27;
    QCheckBox* checkBox4;
    QPushButton* pushButton72;
    QGroupBox* groupBox21_2;
    QButtonGroup* buttonGroup6_2;
    QRadioButton* radioButton11_2;
    QRadioButton* radioButton10_2_2;
    QGroupBox* groupBox25_2;
    QLabel* textLabel3_7_3;
    QLabel* textLabel4_5_3;
    QLineEdit* lineEdit8_3;
    QLineEdit* lineEdit9_3;
    QLabel* textLabel2_8;
    QLabel* textLabel3_8;
    QPushButton* pushButton27_2_6;
    QLabel* textLabel4_2_2;
    QLineEdit* lineEdit_File_PGS;
    QLineEdit* lineEdit_File_PNPS;
    QLineEdit* lineEdit_File_PNGS;
    QLineEdit* lineEdit15;
    QLineEdit* lineEdit16;
    QPushButton* pushButton35_2;
    QPushButton* pushButton75;
    QWidget* WStackPage_15;
    QLabel* textLabel5_2_2;
    QLabel* textLabel1_11;
    QLabel* textLabel2_10;
    QLineEdit* lineEdit17;
    QPushButton* pushButton35_3;
    QPushButton* pushButton27_2_7;
    QCheckBox* checkBox9;
    QWidget* WStackPage_16;
    QPushButton* pushButton27_2_8;
    QGroupBox* groupBox3;
    QFrame* frame6_2_input;
    QLabel* textLabel7_3;
    QLabel* textLabel5_4;
    QLabel* textLabel4_7;
    QLabel* textLabel3_9;
    QLabel* textLabel6_3;
    QLineEdit* lineEdit19_6;
    QLineEdit* lineEdit19_7;
    QLineEdit* lineEdit19_4;
    QLineEdit* lineEdit19_5;
    QLineEdit* lineEdit19_3;
    QButtonGroup* buttonGroup8;
    QLabel* textLabel1_12;
    QLabel* textLabel2_11;
    QLineEdit* lineEdit19;
    QLineEdit* lineEdit19_2;
    QLabel* textLabel2_16;
    QRadioButton* radioButton16;
    QRadioButton* radioButton17;
    QLabel* textLabel1_13;
    QPushButton* pushButton35_4;
    QCheckBox* checkBox8;
    QWidget* thresh;
    QLabel* textLabel2_12;
    QLabel* textLabel1_20;
    QPushButton* pushButton27_2_5_2;
    QLineEdit* lineEdit51;
    QPushButton* pushButton69;
    QPushButton* pushButton75_2;
    QWidget* WStackPage_17;
    QButtonGroup* buttonGroup11;
    QRadioButton* radioButton21_2;
    QRadioButton* radioButton22_2;
    QLabel* textLabel1_14;
    QWidget* WStackPage_18;
    QLabel* textLabel2_18;
    QGroupBox* groupBox32;
    QLineEdit* lineEdit2;
    QLabel* textLabel3_5_2;
    QLabel* textLabel2_5_2;
    QLabel* textLabel1_5_2;
    QLabel* textLabel2_17;
    QLineEdit* lineEdit3_2;
    QLabel* textLabel1_26;
    QLineEdit* lineEdit4_3;
    QLineEdit* lineEdit1;
    QLabel* textLabel4_3_2;
    QLineEdit* swapPercent;
    QLineEdit* mutPercent;
    QWidget* WStackPage_19;
    QLabel* textLabel4_2_2_3;
    QPushButton* pushButton76;
    QPushButton* pushButton27_2_5_2_2;
    QLabel* textLabel1_14_3;
    QWidget* WStackPage_20;
    QLabel* textLabel1_19;
    QWidget* P_Value;
    QPushButton* pushButton74_2_2;
    QLabel* textLabel1_6;
    QWidgetStack* widgetStack6;
    QWidget* WStackPage_21;
    QGroupBox* groupBox14;
    QLabel* textLabel1_7;
    QLabel* textLabel2_13;
    QLabel* pixmapLabel2_1;
    QPushButton* pushButton59_3;
    QPushButton* pushButton29_5;
    QGroupBox* groupBox15;
    QLabel* textLabel2_7;
    QLabel* textLabel2_13_2;
    QLabel* pixmapLabel2_2;
    QPushButton* pushButton59_4;
    QPushButton* pushButton29_2_2;
    QGroupBox* groupBox16;
    QLabel* textLabel3_6;
    QLabel* textLabel2_13_2_2;
    QLabel* pixmapLabel2_3;
    QPushButton* pushButton59_5;
    QPushButton* pushButton29_3_2;
    QGroupBox* groupBox17;
    QLabel* textLabel4_4;
    QLabel* textLabel2_13_2_2_2;
    QLabel* pixmapLabel2_4;
    QPushButton* pushButton59_6;
    QPushButton* pushButton29_4_2;
    QGroupBox* groupBox17_2;
    QLabel* textLabel2_13_2_2_2_2;
    QLabel* textLabel4_4_3;
    QLabel* pixmapLabel2_5;
    QPushButton* pushButton59_7;
    QPushButton* pushButton29_5_2;
    QWidget* WStackPage_22;
    QFrame* frame10_2;
    QLabel* textLabel1_16_2;
    QLineEdit* lineEdit45_2;
    QFrame* frame5_2;
    QLabel* textLabel7_2_2;
    QCheckBox* checkBox3_2;
    QLineEdit* lineEdit11_2;
    QLabel* textLabel5_3_2;
    QLabel* textLabel1_7_2;
    QLabel* textLabel6_4;
    QGroupBox* groupBox4;
    QButtonGroup* buttonGroup5_2;
    QRadioButton* radioButton9_2;
    QRadioButton* radioButton8_2;
    QGroupBox* groupBox6_2;
    QLabel* textLabel3_7_2;
    QLabel* textLabel4_5_2;
    QLineEdit* lineEdit9_2;
    QLineEdit* lineEdit8_2;
    QLabel* textLabel7_4;
    QLabel* textLabel8_2;
    QPushButton* pushButton27_2;
    QLineEdit* lineEdit10_2;
    QLineEdit* lineEdit29;
    QLineEdit* lineEdit30;
    QLineEdit* lineEdit31;
    QPushButton* pushButton35_5;
    QWidget* WStackPage_23;
    QLabel* textLabel2_7_2;
    QLabel* textLabel1_9_2;
    QLabel* textLabel4_6_2;
    QGroupBox* groupBox21_2_2;
    QButtonGroup* buttonGroup6_2_2;
    QRadioButton* radioButton11_2_2;
    QRadioButton* radioButton10_2_2_2;
    QGroupBox* groupBox25_2_2;
    QLabel* textLabel3_7_3_2;
    QLabel* textLabel4_5_3_2;
    QLineEdit* lineEdit8_3_2;
    QLineEdit* lineEdit9_3_2;
    QLabel* textLabel2_9_2;
    QLabel* textLabel1_10_2;
    QLabel* textLabel2_8_2;
    QLabel* textLabel3_8_2;
    QPushButton* pushButton27_2_2;
    QLineEdit* lineEdit_File_PGS_2;
    QLineEdit* lineEdit_File_PNPS_2;
    QLineEdit* lineEdit_File_PNGS_2;
    QLineEdit* lineEdit16_2;
    QLineEdit* lineEdit15_2;
    QPushButton* pushButton35_6;
    QPushButton* pushButton75_4;
    QWidget* WStackPage_24;
    QLabel* textLabel3_6_2;
    QLabel* textLabel2_10_2;
    QPushButton* pushButton27_2_3;
    QLabel* textLabel1_11_2;
    QCheckBox* checkBox9_2;
    QLineEdit* lineEdit17_2;
    QPushButton* pushButton35_7;
    QWidget* WStackPage_25;
    QLabel* textLabel4_4_2;
    QPushButton* pushButton27_2_4;
    QPushButton* pushButton35_8;
    QGroupBox* groupBox3_2;
    QFrame* frame6_2_input_2;
    QLabel* textLabel1_13_2;
    QLabel* textLabel3_9_2;
    QLabel* textLabel4_7_2;
    QLabel* textLabel5_4_2;
    QLabel* textLabel6_3_2;
    QLabel* textLabel7_3_2;
    QButtonGroup* buttonGroup8_2;
    QLabel* textLabel1_12_2;
    QLabel* textLabel2_11_2;
    QLabel* textLabel2_16_2;
    QRadioButton* radioButton17_2;
    QRadioButton* radioButton16_2;
    QLineEdit* lineEdit19_8;
    QLineEdit* lineEdit19_2_2;
    QLineEdit* lineEdit19_5_2;
    QLineEdit* lineEdit19_6_2;
    QLineEdit* lineEdit19_7_2;
    QLineEdit* lineEdit19_3_2;
    QLineEdit* lineEdit19_4_2;
    QCheckBox* checkBox8_2;
    QWidget* WStackPage_26;
    QLabel* textLabel4_2_2_3_2;
    QPushButton* pushButton27_2_2_2;
    QPushButton* pushButton76_2;
    QLabel* textLabel1_14_2;
    QWidget* WStackPage_27;
    QLabel* textLabel3_11;
    QLabel* textLabel1_20_2;
    QPushButton* pushButton27_2_4_2;
    QLineEdit* lineEdit51_2;
    QPushButton* pushButton69_2;
    QPushButton* pushButton75_2_2;
    QWidget* WStackPage_28;
    QLabel* textLabel1_15;
    QPushButton* pushButton27_2_4_2_2;
    QWidget* WStackPage_29;
    QButtonGroup* buttonGroup11_2;
    QRadioButton* radioButton21_2_2;
    QRadioButton* radioButton22_2_2;
    QLabel* textLabel1_14_4;
    QWidget* WStackPage_30;
    QLabel* textLabel1_17;
    QGroupBox* groupBox8;
    QPushButton* pushButton50_3;
    QPushButton* pushButton50_2_4;
    QPushButton* pushButton71_2;
    QGroupBox* groupBox7;
    QPushButton* pushButton71;
    QPushButton* pushButton50;
    QPushButton* pushButton50_2;
    QWidget* WStackPage_31;
    QLabel* textLabel1_24;
    QWidgetStack* widgetStack7;
    QWidget* WStackPage_32;
    QGroupBox* groupBox29;
    QButtonGroup* buttonGroup2_2;
    QCheckBox* checkBox4_2;
    QGroupBox* groupBox29_2;
    QCheckBox* checkBox7;
    QLabel* textLabel2_15;
    QCheckBox* checkBox6;
    QGroupBox* groupBox30;
    QLabel* textLabel1_25;
    QLabel* textLabel3_12;
    QLabel* textLabel4_8;
    QLineEdit* lineEdit53;
    QLineEdit* lineEdit54;
    QPushButton* pushButton81;
    QLabel* textLabel2;
    QPushButton* pushButton2;
    QWidget* WStackPage_33;
    QTextEdit* textEdit1_2;
    QPushButton* pushButton82;
    QLabel* textLabel1_23;
    QPushButton* pushButton4;
    QWidget* WStackPage_34;
    QButtonGroup* buttonGroup2;
    QRadioButton* resultRadio;
    QFrame* line1;
    QRadioButton* radioButton20;
    QRadioButton* orfRadio;
    QRadioButton* predictionRadio;
    QButtonGroup* buttonGroup12;
    QFrame* line2;
    QRadioButton* radioButton21;
    QLabel* computationPart;
    QRadioButton* radioButton22;
    QLabel* textLabel1_27;

    int _orf_n_max;
    int _orf_p_min;
    int _orf_p_max;
    int _min_range;
    int _max_range;
    int _min_range_r;
    int _max_range_r;
    int _min_range_p;
    int _max_range_p;
    int _orf_n_min;

    virtual void selectForm_NI( int pv_ne );
    virtual bool Validation_of_Trimvalues();

public slots:
    virtual void apply();
    virtual void initializeFields();
    virtual void non_interactive_rstat_call();
    virtual void non_interactive_pval_call();
    virtual void InitializeApplication();
    virtual void Initialize_Namespace();
    virtual void browseFile_clicked();
    virtual void acceptPath_Ready_for_Computation();
    virtual void updateStatusView();
    virtual void setGUIState();
    virtual void nextForm_NI();
    virtual void previousForm_NI();
    virtual void linkResults( int nameSpaceid, int resultId );
    virtual void openFile( const char * fn );
    virtual void sequenceFileName_textChanged( const QString & );
    virtual void computeOrfNowPushButton_clicked();
    virtual void goToNextPageORF();
    virtual void goToPreviousPageORF();
    virtual void goToPreviousPageRANDOM();
    virtual void goToNextPageRANDOM();
    virtual void goToNextPageRStatistics();
    virtual void goToPreviousPageRStatistics();
    virtual void goToNextPagePValue();
    virtual void goToPreviousPagePValue();
    virtual void pushButton14_clicked();
    virtual void initialize_max_min_fields();
    virtual void pushButton15_clicked();
    virtual void pushButton20_clicked();
    virtual void pushButton12_clicked();
    virtual void orfRadio_clicked();
    virtual void predictionRadio_clicked();
    virtual void pushButton16_3_clicked();
    virtual void pushButton16_2_clicked();
    virtual void pushButton16_clicked();
    virtual void pushButton19_clicked();
    virtual void radioButton7_clicked();
    virtual void radioButton8_clicked();
    virtual void radioButton9_clicked();
    virtual void radioButton10_clicked();
    virtual void checkBox2_toggled( bool b );
    virtual void pushButton15_released();
    virtual void pushButton26_clicked();
    virtual void widgetStack_aboutToShow( QWidget * );
    virtual void lineEdit3_textChanged( const QString & );
    virtual void enablePusButton14();
    virtual void lineEdit4_textChanged( const QString & );
    virtual void pushButton27_clicked();
    virtual void pushButton28_clicked();
    virtual void pushButton25_pressed();
    virtual void pushButton3_clicked();
    virtual void pushButton16_4_released();
    virtual void pushButton18_released();
    virtual void pushButton19_2_released();
    virtual void pushButton20_2_clicked();
    virtual void pushButton21_clicked();
    virtual void pushButton29_clicked();
    virtual void pushButton29_2_clicked();
    virtual void pushButton29_4_clicked();
    virtual void nearest_neighbour_default( int flag );
    virtual void nearest_neighbour_default_1( int rstat_or_p_flag, int flag, int count );
    virtual void pushButton27_2_5_clicked();
    virtual void pushButton27_2_6_clicked();
    virtual void pushButton27_2_7_clicked();
    virtual void pushButton27_2_8_clicked();
    virtual void pushButton29_5_clicked();
    virtual void pushButton29_2_2_clicked();
    virtual void pushButton29_4_2_clicked();
    virtual void pushButton27_2_clicked();
    virtual void pushButton27_2_2_clicked();
    virtual void pushButton27_2_3_clicked();
    virtual void pushButton27_2_4_clicked();
    virtual void tabWidget2_currentChanged( QWidget * w );
    virtual void pushButton35_clicked();
    virtual void checkBox3_clicked();
    virtual void checkBox3_2_clicked();
    virtual void pushButton45_clicked();
    virtual void directoryChangedWarning();
    virtual void pushButton35_2_clicked();
    virtual void pushButton35_3_clicked();
    virtual void widgetStack5_aboutToShow( int widgetNo );
    virtual void pushButton29_3_pressed();
    virtual void pushButton29_3_released();
    virtual void pushButton35_4_clicked();
    virtual void pushButton27_2_5_2_clicked();
    virtual void pushButton27_2_5_2_2_clicked();
    virtual void pushButton27_2_5_2_3_clicked();
    virtual void pushButton27_2_5_2_4_clicked();
    virtual void pushButton35_5_clicked();
    virtual void pushButton45_2_clicked();
    virtual void pushButton35_6_clicked();
    virtual void pushButton64_clicked();
    virtual void pushButton27_2_2_2_clicked();
    virtual void radioButton9_2_clicked();
    virtual void radioButton8_2_clicked();
    virtual void pushButton35_7_clicked();
    virtual void pushButton35_8_clicked();
    virtual void pushButton27_2_4_2_released();
    virtual void pushButton27_2_4_2_2_released();
    virtual void pushButton29_3_2_pressed();
    virtual void pushButton29_3_2_released();
    virtual void resultRadio_clicked();
    virtual void newSlot();
    virtual void pushButton50_clicked();
    virtual void pushButton50_2_clicked();
    virtual void pushButton50_3_clicked();
    virtual void pushButton50_2_4_clicked();
    virtual void closeSession_clicked();
    virtual void pushButton59_clicked();
    virtual void pushButton59_2_clicked();
    virtual void pushButton59_2_2_released();
    virtual void pushButton59_2_2_pressed();
    virtual void pushButton59_2_3_clicked();
    virtual void pushButton59_6_clicked();
    virtual void pushButton59_5_released();
    virtual void pushButton59_5_pressed();
    virtual void pushButton59_4_clicked();
    virtual void pushButton59_3_clicked();
    virtual void radioButton11_clicked();
    virtual void radioButton10_2_clicked();
    virtual void radioButton10_2_2_clicked();
    virtual void radioButton11_2_clicked();
    virtual void radioButton10_2_2_2_clicked();
    virtual void radioButton11_2_2_clicked();
    virtual void pushButton29_4_3_clicked();
    virtual void pushButton59_2_3_2_clicked();
    virtual void pushButton69_clicked();
    virtual void pushButton29_5_2_clicked();
    virtual void pushButton69_2_clicked();
    virtual void pushButton71_clicked();
    virtual void pushButton71_2_clicked();
    virtual void pushButton25_clicked();
    virtual void checkBox4_stateChanged( int );
    virtual void pushButton72_clicked();
    virtual void pushButton76_clicked();
    virtual void lineEdit8_textChanged();
    virtual void lineEdit9_textChanged();
    virtual void lineEdit8_3_textChanged();
    virtual void lineEdit9_3_textChanged();
    virtual void lineEdit8_2_textChanged();
    virtual void lineEdit9_2_textChanged();
    virtual void lineEdit8_3_2_textChanged();
    virtual void lineEdit9_3_2_textChanged();
    virtual void pushButton76_2_clicked();
    virtual void pushButton59_7_clicked();
    virtual void pushButton2_clicked();
    virtual void evaluateNow();
    virtual void pushButton82_clicked();
    virtual void widgetStack7_aboutToShow( int w );
    virtual void radioButton20_clicked();
    virtual void pushButton4_clicked();
    virtual void pushButton81_clicked();
    virtual void pushButton82_2_clicked();
    virtual void pushButton83_clicked();
    virtual void lineEdit17_textChanged( const QString & );
    virtual void lineEdit17_2_returnPressed();
    virtual void lineEdit17_returnPressed();
    virtual void lineEdit17_2_textChanged( const QString & );
    virtual void pushButton163_clicked();
    virtual void pushButton75_clicked();
    virtual void radioButton21_clicked();
    virtual void radioButton22_clicked();
    virtual void pushButton74_clicked();
    virtual void tabWidget2_selected( const QString & name );
    virtual void timerStateShow();
    virtual void pushButton75_2_clicked();
    virtual void checkBox8_stateChanged( int state );
    virtual void lineEdit61_textChanged( const QString & vs );
    virtual void lineEdit62_textChanged( const QString & vs );
    virtual void radioButton21_2_toggled( bool );
    virtual void radioButton22_2_toggled( bool );
    virtual void checkBox9_clicked();
    virtual void pushButton74_2_clicked();
    virtual void predictionRadio_stateChanged( int state );
    virtual void initEntryForm();
    virtual void radioButton28_stateChanged( int state );
    virtual void radioButton27_stateChanged( int state );
    virtual void openSession_clicked();
    virtual void setSessionVariableAndStart();
    virtual void radioButton33_stateChanged( int state );
    virtual void radioButton34_stateChanged( int state );
    virtual void radioButton29_stateChanged( int state );
    virtual void pushButton75_3_clicked();
    virtual bool updateFolderPathToFileMg();
    virtual void pushButton77_clicked();
    virtual void pushButton78_clicked();
    virtual void pushButton96_clicked();
    virtual void radioButton33_clicked();
    virtual void radioButton34_clicked();
    virtual void radioButton27_clicked();
    virtual void radioButton29_clicked();
    virtual void radioButton27_toggled( bool );
    virtual void pushButton76_3_clicked();
    virtual void pushButton74_2_2_released();
    virtual void pushButton75_2_2_clicked();
    virtual void pushButton75_4_clicked();
    virtual void checkBox8_2_stateChanged( int state );
    virtual void widgetStack6_aboutToShow( int n );
    virtual void radioButton21_2_2_toggled( bool );
    virtual void radioButton22_2_2_toggled( bool );

protected:
    QGridLayout* groupBox37Layout;
    QGridLayout* groupBox37_2Layout;
    QGridLayout* groupBox41Layout;
    QVBoxLayout* buttonGroup13Layout;
    QVBoxLayout* layout1;
    QVBoxLayout* layout2;

protected slots:
    virtual void languageChange();

private:
    QTime *t;

    QPixmap image0;
    QPixmap image1;

    void init();

};

#endif // FORM1_H
