######################################################################
# Automatically generated by qmake (1.07a) Wed Aug 22 15:42:54 2007
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += createDirectory.ui.h
INTERFACES += createDirectory.ui
